import "./css/modern-normalize.css";
import css from "./css/styles.css";
import "./css/product.css";
import "./css/modal.css";
import "./js/getForm.js";
import "./js/modal.js";
import "./js/form.js";
import "./js/elements.js";
import "./js/products.js";
import "./js/coctails-party.js";
